routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//For User Authentication:
// php artisan make:auth
// Authentication scaffolding generated successfully


//php artisan down - Maintenance mode 503 Service Unavailable
// php artisan up - to make live

//how to make middleware 
// php artisan make:middleware TestMiddleware - ater creating have to register controller or route
// register in kernal.php 

//URL Helpers
//action="{{url('/contact')}}" it gives complete path http://127.0.0.1
// and one is name('contact.create')


//Php artisan route:list


//NPM , Node , Vue , Webpack
/*
npm -v
node -v
npm install
webpack is a module bundler. Its main purpose is to bundle JavaScript files for usage in a browser, yet it is also capable of transforming, bundling, or packaging .

Webpack is a module bundler that takes your development assets (like Vue components and plain Javascript files) and combines them into so called bundles. This is different from simply concatenating and minifying JavaScript files. Simply put, with webpack bundles only the modules required on the current page are loaded.

npm run dev

npm run watch // if go any issue delete node modules folder and re install 
rm -rf node_modules/ && npm install


 * We'll load the axios HTTP library which allows us to easily issue requests
 * to our Laravel back-end. This library automatically handles sending the
 * CSRF token as a header based on the value of the "XSRF" token cookie.

 Frontend Presets for React, Vue, Bootstrap & Tailwind CSS

 preset is swap the front-end scaffolding for the application
 none , bootstrap, vue , react
 php artisan preset react
 npm install && npm run dev
 php artisan preset none it will remove scaffolding

 In resource folder check js/components(Example.js) & js/app.js & js/bootstrap.js

 composer require laravel-frontend-presets/tailwindcss
    npm install && npm run dev && npm run dev

    Events & listeners:

 php artisan make:mail WelcomeNewUserEmail --markdown=emails.new-welcome
 

*/

Route::get('/', function () {
    return view('home');//welcome
});
// Route::get('/contact', function () {
//     return view('contact');
// });
// Route::view('/contact', 'contact');
Route::get('/contact-us', 'ContactFormController@create')->name('contact.create');
Route::post('/contact-us', 'ContactFormController@store')->name('contact.store');;
Route::get('/about', function () {
    // return 'About Us';
    return view('about');
})->middleware('test');

/* Route::get('/customers','CustomersController@index'
    // $customers = ["uday","Kumar","Reddy"];
    // return view('internals.customers',['customers'=>$customers]);
); */


/* Route::get('/customers','CustomersController@index');
Route::get('/customers/create','CustomersController@create');
Route::post('/customers','CustomersController@store');
Route::get('/customers/{customer}','CustomersController@show');
Route::get('/customers/{customer}/edit','CustomersController@edit');
Route::patch('/customers/{customer}','CustomersController@update');
Route::delete('/customers/{customer}','CustomersController@destroy'); */
Route::resource('/customers','CustomersController');//->middleware('auth')

//To create like resource controller php artisan make:controller TestController -r
//To  make resource controller with route model binding :  php artisan make:controller Test2Controller -r -m Customer
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
// Route::get('/home', 'HomeController@index');//->name('home')

app/Customer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    //

    //Fillable Example
    // protected $fillable = ['name','email','active'];

    //Guarded is opposite of fillable
    protected $guarded = [];//'name' means name will not allow for mass assignment


    // Undefined index:
    protected $attributes = [
        'active'=>1//Default be Active in Add form of Customer Active Secletion Drop down
    ];

    public function scopeActive($query){
        return $query->where('active',1);
    }

    public function scopeInactive($query){
        return $query->where('active',0);
    }

    public function company(){
        return $this->belongsTo(Company::class);
    }

    public function getActiveAttribute($attribute){
        return $this->activeOptions()[$attribute];
    }

    public function activeOptions(){
       return  [
           1 =>'Active',
           0 =>'Inactive',
           2 =>'In-Progress'
       ];
    }
}

app/Http/Controllers/CustomersController.php
<?php

namespace App\Http\Controllers;



use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use App\Mail\WelcomeNewUserEmail;

use App\Events\NewCustomerHasRegisteredEvent;


use App\Customer;

use App\Company;

class CustomersController extends Controller
{

    public function __construct(){
        // $this->middleware('auth');
        // $this->middleware('auth')->only('create');
        // $this->middleware('auth')->except('index');
    }
    //Follow the resource controller pattern for method names
/*     Actions Handled By Resource Controller
Verb	URI	Action	Route Name
GET	/photos	index	photos.index
GET	/photos/create	create	photos.create
POST	/photos	store	photos.store
GET	/photos/{photo}	show	photos.show
GET	/photos/{photo}/edit	edit	photos.edit
PUT/PATCH	/photos/{photo}	update	photos.update
DELETE	/photos/{photo}	destroy	photos.destroy */
    public function index(){
        //php artisan migrate:fresh
        // $customers = ["uday","Kumar","Reddy"];
        // $customers = Customer::all();
        // dd($customers);
        

        // dd($activecustomers);
        // dd($activecustomers[0]->company->name);//Infosys
        // $inactivecustomers = Customer::where('active',0)->get();
        // $activecustomers = Customer::where('active',1)->get();
        // $inactivecustomers = Customer::inactive()->get();

        // $customers = Customer::all();
        $customers = Customer::paginate(10);

        //Eloquent ORM: It in build ORm , it providers option to intere=acts with databse very easy
        return view('customers.index',['customers'=>$customers]);
        // ['actcustomers'=>$activecustomers,'inactcustomers'=>$inactivecustomers]
    }

    public function create(){
        
        $company = Company::all();
       
        // 
        // Undefined variable: customer
         $customer = new Customer();
        return view('customers.create',['companylist'=>$company,'customer'=>$customer]);
    }

    public function store(Request $request){
            // print_r($request); Don't Use this bcz too much data it is providing (unwanted data)
            // dd(request()); dd(request('name'));
            //419 page expired CSRF
            // "_token" => "vNBJTn0JavpzTQLfDiEsRxV3YRtasO4xDrMxPyvo","name" => "hello"

            //Validate here to avoid error like SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null
          /*   $data = request()->validate([
                'name'=>'required | min:3',
                'email'=>'required | email',
                'active'=>'required',
                'company_id'=>'required'
                // 'random'=>''//optional field ; no validation
            ]); */
            /* $data = $request->validate([
                'name' => 'required',
            ]); */
            // Spelling Mistake In required place i gave like requred Method Illuminate\Validation\Validator::validateRequred does not exist.

                // dd($data);//name,email,active,random
                // Add [name] to fillable property to allow mass assignment on [App\Customer].

                // SQLSTATE[HY000]: General error: 1364 Field 'company_id' doesn't have a default value = Means check fillable in model
                // $customers = Customer::create($data);
                // validateRequest
                $customers = Customer::create($this->validateRequest());

                //Send A welcome Mail to the user Using Event & Listeners:
                // php artisan make:mail WelcomeNewUserEmail --markdown=emails.new-welcome


                //To make our controller code clean - we are using Events & Listeners 
                /* Mail::to($customers->email)->send(new WelcomeNewUserEmail());
                //Register to newsletters
                dump("Registered to News Letters");
                //Send Slack notification to Admin
                dump('Slack message here'); */
                //make:event  make:listeners 
                // One event & 3 listerens (Mail sending 2. Registered News Letters 3.Slack Messages)
                // print_r($customers->email);
                event( new NewCustomerHasRegisteredEvent($customers));
                //php artisan make:event NewCustomerHasRegisteredEvent
                // now create listers 
                // php artisan make:listener WelcomeNewCustomerListener
                // Mail::to($customers->email)->send(new WelcomeNewUserEmail()); This line moved to Listeners handle method
                //Now we have create connection in between Event & Listeners
                //Service providers
                dump("Registered to News Letters Customer Controller");
                //event:generate
                // php artisan event:generate  - Auto matically generates with names we provided in servvice providers

                // Queue - User don't have to wait it can run in background either image upload or in any case
                //.env QUEUE_CONNECTION = sync
                //Queues: Database Driver
                //queue:table - create a migration for the queue jobs database table
                //php artisan queue:table - it will create jobs table and migratio also
                //.env change sync to database
                //php artisan queue:work - Strat processing jobs on the queue as a daemon
                //if queue jobs not working then restart serve again
                //php artisan config:clear php artisan cache:clear
                //php artisan queue:work &  it gives process id
                //jobs 
                //jobs -l
                //KILL processID
                //php artisan queue:work > storage/logs/jobs.log &



                








                // $customers = Customer::create(request()->all());//Not good practice
                

           /*  $customers = new Customer();
            $customers->name = $request->name;
            $customers->email = request('email');
            $customers->active = request('active');
            $customers->save(); */
            // return back();

            // return redirect('/customers');

            //Now i want to add email filed in customers 
            // so In migration added $table->string('email'); php artisan migrate:rollback ; php artisan migrate
    }   


    public function show(Customer $customer){

        // $customer has to match in the route file & controller 


        // dd($customer);
        // $customer = Customer::find($customer);

        // Trying to get property 'name' of non-object  - If we access not having id then it shows this error  , so to overcome this we are using below format

        // $customer = Customer::where('id',$customer)->firstOrFail();//HTTP ERROR 404 if id data not found

        // Eloquent Route Model Binding - Means 
        // When injecting a model ID to a route or controller action, you will often query the database to retrieve the model that corresponds to that ID. Laravel route model binding provides a convenient way to automatically inject the model instances directly into your routes. For example, instead of injecting a user's ID, you can inject the entire User model instance that matches the given ID.

        return view('customers.show',['customer'=>$customer]);
    }

    public function edit(Customer $customer){
        $company = Company::all();
        return view('customers.edit',['customer'=>$customer,'companylist'=>$company]);
    }
    public function update(Customer $customer){
       /*  $data = request()->validate([
            'name'=>'required | min:3',
            'email'=>'required | email',
            'active'=>'required',
            'company_id'=>'required'
        ]); */
        // $customer->update($data);
        $customer->update($this->validateRequest());
        

        return redirect('customers/'.$customer->id);

    }


    private function validateRequest(){
        return request()->validate([
            'name'=>'required | min:3',
            'email'=>'required | email',
            'active'=>'required',
            'company_id'=>'required'
            // 'random'=>''//optional field ; no validation
        ]);
    }


    public function destroy(Customer $customer){

        $customer->delete();

        return redirect('/customers');
    }


    /*
    * some extra stff
    * php artisan make:command AddCompanyCommand
    * protected $signature = 'contact:company';
    * protected $description = 'Adds A new Company';
    * php artisan contact:company
    * php artisan contact:company 'A New Company'

    */
    /*
    *Closure: Closure based commands : routes/console.php 
    php artisan inspire

    Company::whereDoesntHave('customers')
    ->get()
    ->each(function($company){
        $company->delete();
        $this->warn('Deleted '.$company->name);
    });
    */
    /* Model Factories: Fake data 
        Tinker - $c = \App\User::all()->pluck('name')
        factory(\App\User::class,3)->create();
        
        php artisan make:factory CompanyFactory -m Company
    */
    /* Database & Table Seeders:
        php artisan db:seed 
        php artisan make:seeder UsersTableSeeder

        factory(\App\Users::class,3)->create();  - use seeders or Tinker
        php artisan db:seed

        $this->call(UsersTableSeeder::class);
        ReflectionException  : Class CompaniesTableSeeder does not exist
        composer dump-autoload
        php artisan db:seed
    */

    /*
    Image Upload :
    Validate - Image is optional then use tap method , hasFile('image')
    $this->storeImage($customer);


    storage:link

    */

    /**
     * 
     * Telescope is providing a dashboard shows the request time limit and same same way , queries triggers all triggers will show herelike trihggering 
     * 
     * Lazy Loading & Eagar Loading ...?
     * 
     * use with('company')  it modify like comapny_id in (1,2,34,5,68,7,9,);
     * 
     * 
     * Policy
     */
}

resources/views/customers/create.blade.php
@extends('layouts.app')

<!-- @section('title')
    Customrer Liast
@endsection -->

@section('title','Add New Customer')



@section('content')

<!-- <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about">About US</a></li>
    <li><a href="/contact">Contact Us</a></li>
    <li><a href="/customers">Customers List</a></li>
</ul> -->


<?php
// foreach($customers as $cust){
//     echo '<li>'.$cust.'</li>';
// }
?>

<div class="row">
    <div class="col-12">
        <h1>Add New Customers</h1>

    </div>
</div>

<div class="row">
    <div class="col-12">
        <!-- customers post route -->
        <form action="/customers" method="post">
           @include('customers.form')
                <input type="submit" value="Add" class="btn btn-primary">
            </div>

        </form>
    </div>
</div>







@endsection

resources/views/customers/edit.blade.php
@extends('layouts.app')

<!-- @section('title')
    Customrer Liast
@endsection -->

@section('title','Edit Details for '.$customer->name)



@section('content')

<!-- <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about">About US</a></li>
    <li><a href="/contact">Contact Us</a></li>
    <li><a href="/customers">Customers List</a></li>
</ul> -->


<?php
// foreach($customers as $cust){
//     echo '<li>'.$cust.'</li>';
// }
?>

<div class="row">
    <div class="col-12">
        <h1>Edit details for Customers {{$customer->name}}</h1>

    </div>
</div>

<div class="row">
    <div class="col-12">
        <!-- customers post route -->
        <!-- <form action="/customers/{{$customer->id}}" method="post"> -->
        <form action="{{route('customers.update',['customer'=>$customer] )}}" method="post">
            @method('PATCH')
            @include('customers.form')
                <input type="submit" value="Edit" class="btn btn-primary">
            </div>

        </form>
    </div>
</div>







@endsection

resources/views/customers/form.blade.php
@csrf
            <div class="form-group">
                <label for="">Name</label>
                <input type="text" name="name" id="name" value="{{old('name') ?? $customer->name}}" class="form-control">
                <div>{{$errors->first('name')}}</div>
            </div>

            <div class="form-group">
                <label for="">Email</label>
                <input type="text" name="email" id="email" value="{{old('email') ?? $customer->email}}" class="form-control">
                <div>{{$errors->first('email')}}</div>

                <div class="form-group">
                    <label for="company_id"></label>
                    <select name="company_id" id="company_id" class="form-control">
                        <option value="">Select Company</option>
                        @foreach($companylist as $comp)
                        <option value="{{$comp->id}}" {{$comp->id==$customer->company_id ? 'selected':''}}>{{$comp->name}}</option>
                        @endforeach
                    </select>
                </div>

                <!-- Undefined index: check model attributes default -->
                <div class="form-group">
                    <label for="active"></label>
                    <select name="active" id="active" class="form-control">
                        <option value="">Select</option>
                        @foreach($customer->activeOptions() as $activeOptionsKey => $activeOptionsValue)
                        <option value="{{$activeOptionsKey}}" {{$customer->active==$activeOptionsValue ? 'selected' : ''}}>{{$activeOptionsValue}}</option>
                       
                        @endforeach
                        <!-- <option value="1" {{$customer->active=='Active' ? 'selected' : ''}}>Active</option>
                        <option value="0" {{$customer->active=='Inactive' ? 'selected' : ''}}>Inactive</option> -->
                    </select>
                </div>

resources/views/customers/index.blade.php
@extends('layouts.app')

<!-- @section('title')
    Customrer Liast
@endsection -->

@section('title','Customrer List')



@section('content')

<!-- <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about">About US</a></li>
    <li><a href="/contact">Contact Us</a></li>
    <li><a href="/customers">Customers List</a></li>
</ul> -->


<?php
// foreach($customers as $cust){
//     echo '<li>'.$cust.'</li>';
// }
?>

<div class="row">
    <div class="col-12">
        <h1>Customers</h1>

        <p><a href="/customers/create">Add New Customer</a></p>

    </div>
</div>

@foreach($customers as $cust)
<div class="row">

        <div class="col-3"><a href="/customers/{{$cust->id}}">{{$cust->id}}</a></div>
        <div class="col-3">{{$cust->name}}</div>
        <div class="col-3">{{$cust->company->name}}</div>
        <div class="col-3">{{$cust->active}}</div>
        <!-- <div class="col-3">{{$cust->active == 1? 'Active' : 'In-Active'}}</div> -->
        <!-- Use Eloquent Accessors for Change Active & In-Active Text-->
        <!-- getActiveAttribute In Customer Model  -->
</div>
@endforeach


{{$customers->links()}}
<?php 
// <div class="row">

//     <div class="col-6">
//         <h3>Active Customers</h3>
//         <ul>
//             @foreach($actcustomers as $cust)
//             <li>{{$cust->name}} {{$cust->email}} {{$cust->company->name}}</li>
//             @endforeach
//         </ul>
//     </div>

//     <div class="col-6">
//         <h3>IN- Active Customers</h3>
//         <ul>
//             @foreach($inactcustomers as $cust)
//             <li>{{$cust->name}} {{$cust->email}} {{$cust->company->name}}</li>
//             @endforeach
//         </ul>
//     </div>
// </div>

?>


<div class="row">
    <div class="col-12">
        <?php 
        // @foreach($companylist as $company)
        // <h3>{{$company->name}}</h3>
        // <ul>
        //     @foreach($company->customers as $cust)
        //     <li> {{$cust->name}}</li>
        //     @endforeach
        // </ul>
        // @endforeach

        ?>

    </div>
</div>



@endsection

resources/views/customers/show.blade.php
@extends('layouts.app')

<?php
//  @section('title')
//     Customrer Liast
// @endsection 
?>

@section('title','Details of '.$customer->name)



@section('content')

<!-- <ul>
    <li><a href="/">Home</a></li>
    <li><a href="/about">About US</a></li>
    <li><a href="/contact">Contact Us</a></li>
    <li><a href="/customers">Customers List</a></li>
</ul> -->


<?php
// foreach($customers as $cust){
//     echo '<li>'.$cust.'</li>';
// }
?>

<div class="row">
    <div class="col-12">
        <h1>Details for {{$customer->name}}</h1>
        <p><a href="/customers/{{$customer->id}}/edit">Edit</a></p>


        <form action="/customers/{{$customer->id}}/" method="post">

        @method('DELETE')
        @csrf

        <button type="submit" class="btn btn-danger">Delete</button>
        </form>

    </div>
</div>

<div class="row">
    <div class="col-12">
        <p><strong>Name:</strong>{{$customer->name}}</p>
        <p><strong>Email:</strong>{{$customer->email}}</p>
        <p><strong>Company:</strong>{{$customer->company->name}}</p>
    </div>
</div>







@endsection